### ISSUE TITLE
Server Error when downloading backup files via Modx Manager

### ISSUE THREAD

**Issue by terrybarth** [jdaehne/BackupMODX#1]
I'm loving this new Extra! I tried this on a several installations now. I love how easy this is. Thank you!

I just tried to download the backup files using the Modx file manager (right click, select download). In each case, I got this error:

The website encountered an error while retrieving http://xxxxxx.com/connectors/index.php?action=browser/file/download&download=1&file=backup/xxxxxxx_xxx_20160107-151624_files.tar&HTTP_MODAUTH=modx54774f3c18ef99.79252889_1568ed6fa804bb3.51837111&source=1&wctx=undefined. It may be down for maintenance or configured incorrectly.

I am able to download the files via FireFTP with no problem.

Hosted on Hostmonster shared server
Modx is 2.4.2-pl (traditional)
PHP Version 5.4.43

**Comment by jdaehne** [comment]
Hi terrybarth,

thank you for that nice feedback - and sorry for my late answer. I tried to download the files via the modx-file-manager as well and i got an error too. I think that is probably because of the file size.

I normaly just click on the file-link inside the widget or right-click and "save as", after the backup is finished: After the backup is done, there should be 3 links to the files to directly download them inside the widget. Does that work for you too?

best regards,
Jan

**Comment by terrybarth** [comment]
Yes, the links within the widget do work. However you have to download them immediately. After the manager refreshes the links disappear.

**Comment by jdaehne** [comment]
Ok, that is good to know... but i think i can't do anything about that error trying to download the backup-files from the modx-file-manager. I think this is because of a file-size-limit or something...

I will have a look for it and figure that out.

You are right. It may would be helpful to keep this links show up in the widget as long as the backups exist.

**Comment by Jako** [comment]
Should be solved with 3.0.0
