### ISSUE TITLE
AJAX Error

### ISSUE THREAD

**Issue by EkoOne** [jdaehne/BackupMODX#18]
When downloading Files it throws a **Failing AJAX** error and the download hangs. Refreshing the page is the only way to stop it but of course the download does not complete.

![modx_backup](https://user-images.githubusercontent.com/1754223/50552025-3c4b5e00-0c50-11e9-9985-464adab0124a.png)

**Comment by kolbykruger** [comment]
I am getting the exact same error. MODX version 2.7.0

**Comment by jdaehne** [comment]
@kolbykruger @EkoOne ok, thanks for the report. This is very strange, because AJAx is not involved in the download at all. Maybe this error is caused because of a memory limit of php for large files. I fixed this in the new version 2.0.1

If you still get this error please let me know.

**Comment by EkoOne** [comment]
I no longer get the AJAX error, but the backup still hangs. The progress animation has been running for over 2 hours and it still hasn't completed on v.2.7.0. I've tried three different browsers and it's the same problem.

**Comment by wintik1** [comment]
I have the same error version 2.7.2

**Comment by terrybarth** [comment]
I'm seeing this error today on a site running modx 2.7.3, php ver 7.13.17, memory limit 256M, backup version 3.0.1.

I've seen this problem on and off over the years. Sites hosted on Godaddy often have this problem.

**Comment by jdaehne** [comment]
@terrybarth this is a more or less a general problem with the server-timeout. The problem is, that zipping up all the files takes longer then the allowed server-time or exceeds the server memory. Then the server just stops and the backup breaks.

The idea of a workaround is to split up the backup process in small parts and redo the process until every file is completed. That way the server limits (time/memory) will hopefully never be hit. But that is just the plan for the next version and not implemented right now.

At the moment it is hard to find some time to implement this. But i hopefully will find some time in the next months.

**Comment by terrybarth** [comment]
Thanks for this. I realized that I had not excluded the backup folder from the backup process so it just got bigger each time. I just reran it and it works now.  Perhaps that could be a default setting? Thank you!

**Comment by Jako** [comment]
It should be a default setting according to the code: https://github.com/jdaehne/BackupMODX/blob/master/core/components/backupmodx/src/Backup/Backup.php#L61

**Comment by levkoi** [comment]
I have the same error. Modx 2.7.3, PHP Version 5.6.40, memory limit 1024M, backupMODX  version 3.0.1

**Comment by Jako** [comment]
BackupMODX 3.0.2 now has a timelimit system setting that works on both sides (javascript call + connector answer) and will correctly return a timeout issue now.
